CI: detect failure of example files

diff --git a/.github/workflows/test_examples.yml b/.github/workflows/test_examples.yml
--- a/.github/workflows/test_examples.yml
+++ b/.github/workflows/test_examples.yml
@@ -53,16 +53,29 @@ jobs:
 
     - name: Test example files
       run: |
+        set -e
         source venv/bin/activate
         python3 -m pip install jupytext
-        python3 -m pip list
         cd docs/examples
-        for f in *.ipynb
-        do
-            jupytext --check  pytest --warn-only $f
+
+        EXIT_CODE=0
+
+        echo "🔍 Testing notebooks..."
+        for f in *.ipynb; do
+          echo "➡️  Running: $f"
+          if ! jupytext --check "pytest {}" "$f"; then
+            echo "❌ Failure in $f"
+            EXIT_CODE=1
+          fi
         done
 
-        for f in *.py
-        do
-            jupytext --check pytest --warn-only $f
+        echo "🔍 Testing scripts..."
+        for f in *.py; do
+          echo "➡️  Running: $f"
+          if ! jupytext --check "pytest {}" "$f"; then
+            echo "❌ Failure in $f"
+            EXIT_CODE=1
+          fi
         done
+
+        exit $EXIT_CODE
